com.epam.homework.task5 (tikhonov)
elefus/epam-core-04-2018 pull request #110
Opened 2018-04-22 18:57 UTC by akalji

2018-04-26 12:32 UTC, igorignatyev approved these changes
Я бы заменил agreeable на consonant :D

2018-04-26 14:12 UTC, akalji commented
@igorignatyev это пасхалка. Так и было задумано.

2018-04-26 16:36 UTC, igorignatyev commented
В таком случае, апплодирую стоя!

2018-04-30 14:46 UTC, elefus requested changes
На занятии рассмотрели возможные способы повышения читаемости)

2018-04-30 20:25 UTC, akalji commented
@elefus, syntax has been improved =)

2018-04-30 22:58 UTC, elefus approved these changes

2018-05-01 18:15 UTC, Gradder approved these changes

2018-05-01 20:57 UTC, merged