com.epam.homework.task8 (tikhonov)
elefus/epam-core-04-2018 pull request #147
Opened 2018-04-28 21:19 UTC by akalji

2018-04-29 08:02 UTC, zkuru approved these changes

2018-04-29 11:45 UTC, Ilya21 commented
А почему у тебя здесь коммиты с 7 задачи?

2018-04-29 12:08 UTC, LicenserX approved these changes

2018-05-02 09:29 UTC, Dgafar approved these changes

2018-05-02 18:20 UTC, elefus requested changes
Как в эту ветку попали коммиты 7 задачи?

2018-05-02 18:32 UTC, akalji commented
@elefus не знаю. И не представляю пока как исправлять

2018-05-02 18:42 UTC, Ilya21 commented
У меня была проблема эта. Скорее всего ты создал ветку находясь в ветке task7. 
Я сохранил решение задачи, снес ветку и создал заново по нормальному из ветки master)

2018-05-10 17:49 UTC, closed without merging