com.epam.homework.task7 (savin)
elefus/epam-core-04-2018 pull request #219
Opened 2018-05-04 20:27 UTC by johnnybarden

Task 7 completed.

2018-05-04 23:42 UTC, Ilya21 requested changes
В этой и во всех предыдущих задачах присутствуют коммиты из прошлых задач. Так это не должно работать. 
Для каждой задачи - отдельная ветка

2018-05-05 06:48 UTC, johnnybarden commented
А как это исправить?

2018-05-05 09:03 UTC, Ilya21 commented
Как ПРАВИЛЬНО исправить я точно не знаю, можно спросить Николая.))
Но у меня тоже была схожая проблема, и для того, чтобы исправить, я не придумал ничего лучше, чем снести неправильную ветку и сделать все заново, предварительно сохранив весь код отдельно)
Коммиты собрались в кучу, потому что скорее всего ты либо ветку не из той точки создаешь, либо еще где нибудь косяк)
Обрати внимание, что новую ветку нужно создавать каждый раз, находясь в ветке мастер, тогда они отдельно получатся. Внимательно перепрочти FAQ, который в слаке висит, может там еще найдешь почему косяк, и что получилось неправильно)

2018-05-06 06:27 UTC, johnnybarden commented
Точно. Дело в том, скорее всего, что новые ветки я создавал не из Мастера. Попробую переделать скоро.

2018-05-26 09:25 UTC, closed without merging