com.epam.homework.task11 (kobzar)
elefus/epam-core-04-2018 pull request #225
Opened 2018-05-06 18:23 UTC by TarasKobzar

Complete.

2018-05-10 18:06 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
А интерес задачи разве был не в том, чтобы никакими структурами не пользоваться?

2018-05-10 18:06 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +        return valueList.size() == 1 ? valueList.get(0) : sum(valueList);
Мне кажется в плане читабельности сложная запись

2018-05-10 18:09 UTC, akalji requested changes
Рекурсивно удалять из списка цифр - читерство ИМХО

2018-05-10 18:09 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
А интерес задачи разве был не в том, чтобы никакими структурами не пользоваться?

2018-05-10 19:47 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Под структурами ты подразумеваешь коллекцию List?

2018-05-10 19:49 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Да. Просто добавить в лист все цифры, складывать и удалять из него рекурсивно пока не пусто - КМК это не совсем то что требовалось.

2018-05-10 20:15 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Я намека на использование какого-то конкретного способа в условии задачи не увидел. Оно вообще в этой задаче краткое очень. Решить с помощью рекурсии. Коллекциями начали пользоваться уже с середины заданий. Вначале я не прибегал к коллекциям. Реализовывал функционал через массив. Но пора бы уже. Тут даже не в коллекции как таковой дело. А именно, чтобы решить через рекурсию. А не просто пробежаться по цифрам в массиве и их сложить. А здесь коллекция потому, что решение через массив не придаст каких-то дополнительных умственных проблем, а вот код засорится. Будь тут массив, логика была бы такая же. Только пришлось бы сделать цикл, который пробегает, проверяет на 0, складывает и вместо удаления присваивает 0. Дополнительной задачи для разрешения это не добавляет.

2018-05-10 20:16 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Так и массив не нужен.

2018-05-10 20:18 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
А, я вообще что-то не то делаю? Что-то другое надо?

2018-05-10 20:19 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Посмотри мое решение. Не претендую на идеологическую точность, но считаю имелось в виду именно это. Рекурсия в чистом виде

2018-05-10 20:23 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
В том плане, что зачем собственно говоря сам массив... Как бы масло масляное. Но если не согласен - спросим завтра.

2018-05-10 20:25 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Пока мое решение не пройдет тесты, я не смотрю решения у других. Если мое не пройдет тесты, хочу сам придумать правильное решение.

2018-05-10 20:26 UTC, akalji commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
ОК. Твое решение пройдет тесты, но по моему мнению решение не соответствует постановке задачи.

2018-05-10 20:30 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
Может быть я и не понял задачу. Завтра у Николая спрошу. Спасибо, что подметил.

2018-05-19 10:09 UTC, TarasKobzar commented on src/main/java/com/epam/homework/Task11.java
> +    static int sum(List<Integer> valueList){
А ты случайно не "Request changes"?

2018-05-19 10:12 UTC, akalji approved these changes

2018-05-19 13:45 UTC, johnnybarden approved these changes

2018-05-24 08:25 UTC, Dgafar approved these changes

2018-05-24 08:51 UTC, merged