com.epam.homework.task2 (tikhonov)
elefus/epam-core-04-2018 pull request #3
Opened 2018-04-15 16:37 UTC by akalji

2018-04-15 17:14 UTC, Ilya21 commented on src/main/java/com/epam/homework/Task2.java
> +package com.epam.homework;
Test

2018-04-15 17:33 UTC, Ilya21 commented on src/main/java/com/epam/homework/Task2.java
> +package com.epam.homework;
Test

2018-04-15 17:35 UTC, Ilya21 commented
Я что-то сломал походу)

2018-04-15 17:39 UTC, Ilya21 approved these changes

2018-04-16 22:36 UTC, lostforstupid approved these changes

2018-04-16 22:44 UTC, MalyshevI commented on src/main/java/com/epam/homework/Task2.java
> +        Comparator<String> comparator = (o1, o2) -> o1.length() - o2.length();
А что значит 47 строчка кода у тебя?

2018-04-16 22:50 UTC, MalyshevI requested changes
Данная реализация не учитывает данное условие задачи: "В случае, если длины строк совпадают - упорядочить их в лексикографическом порядке."

2018-04-17 04:39 UTC, akalji commented on src/main/java/com/epam/homework/Task2.java
> +        Comparator<String> comparator = (o1, o2) -> o1.length() - o2.length();
Лямбда выражение. Вроде вчера этот пример разбирали

2018-04-17 20:47 UTC, m1nsk commented on src/main/java/com/epam/homework/Task2.java
> +        Comparator<String> comparator = (o1, o2) -> o1.length() - o2.length();
Только этот компаратор не учитывает "В случае, если длины строк совпадают - упорядочить их в лексикографическом порядке."

2018-04-17 20:48 UTC, akalji commented on src/main/java/com/epam/homework/Task2.java
> +        Comparator<String> comparator = (o1, o2) -> o1.length() - o2.length();
да, я не учел это. Скоро исправлю

2018-04-18 10:06 UTC, MalyshevI approved these changes

2018-04-18 21:08 UTC, merged