com.epam.homework.task6 (ignatev)
elefus/epam-core-04-2018 pull request #368
Opened 2018-06-02 16:39 UTC by igorignatyev

2018-06-02 19:32 UTC, ghost requested changes
Мне кажется, что программа работает некорректно:
у тебя если первое слово удовлетворяет условию - сразу же все остальные слова не проверяются и программа завершается, попробуй протестить с набором слов 
2
am bm
увидишь, что второе слово не будет выведено

p.s. могу ошибаться

2018-06-05 18:31 UTC, ghost approved these changes

2018-06-05 20:23 UTC, TerJkee approved these changes

2018-06-06 22:14 UTC, goponenkoev approved these changes

2018-06-08 12:19 UTC, merged