com.epam.homework.task1 (abuzyarova)
elefus/epam-core-04-2018 pull request #42
Opened 2018-04-17 18:12 UTC by zkuru

2018-04-18 09:27 UTC, lostforstupid approved these changes

2018-04-18 10:09 UTC, YellowFatCat commented on src/main/java/com/epam/homework/Task1.java
> +        String tmp;
На мой взгляд, лучше объявить tmp и tmpLength поближе к месту их использования (и, может быть, вообще не стоит расширять область их видимости до всего метода, если они используются только в цикле?)

2018-04-18 10:20 UTC, YellowFatCat commented
.class-файл, наверное, лучше не коммитить :)

2018-04-18 11:04 UTC, zkuru commented on src/main/java/com/epam/homework/Task1.java
> +        String tmp;
@YellowFatCat угу. я думала в целях оптимизации, но в слаке уже написали, что для этого не стоит инициализировать вне цикла. Ща поправлю)

2018-04-18 11:17 UTC, zkuru commented
@YellowFatCat да. оно случайно вышло :D

2018-04-18 17:51 UTC, heydancer approved these changes

2018-04-19 15:35 UTC, elefus requested changes
Удалить .class-файл

2018-04-20 07:26 UTC, elefus approved these changes

2018-04-20 07:27 UTC, merged